export default {
  comments:[
    {
      id:11,//当前评论的id
      userId:101,//作者id,娇友id
      userIcon:'e5.jpg',//作者头像，娇友头像
      userNickName:'小萝莉',//作者昵称
      publishTime:'2018-08-23 08:10:00',
      sex:1,//0男1女2不限
      age:23,
      vipType:'SVIP3',
      deposit:1,//保证金
      demand:{
        idcard:1,
        car:1,
        house:0,
        health:0
      },
      reply:'564',//评论的回复数
      praise:'132',//评论的点赞数
      myPraise:0,//当前用户是否点赞0否1是
      replyContent:'有人问我思念到极致是什么感觉。 我曾经发了句晚安给她 一晚上醒来七次看手机信息。 就是那种可怕的朦朦胧胧的意识 梦里都梦到她好',
      replys:{
        id:1,//评论id
        userId:1001,
        userNickName:'痴心的人',
        parentId:null,
        parentNickName:null,
        comment:'做人要厚道',
      }
    },
    {
      id:12,//当前评论的id
      userId:102,//作者id,娇友id
      userIcon:'e5.jpg',//作者头像，娇友头像
      userNickName:'小萝莉',//作者昵称
      publishTime:'2018-08-20 08:10:00',
      sex:1,//0男1女2不限
      age:23,
      vipType:'SVIP3',
      deposit:1,//保证金
      demand:{
        idcard:1,
        car:1,
        house:0,
        health:0
      },
      reply:'564',//评论的回复数
      praise:'132',//评论的点赞数
      myPraise:0,//当前用户是否点赞0否1是
      replyContent:'有人问我思念到极致是什么感觉。 我曾经发了句晚安给她 一晚上醒来七次看手机信息。 就是那种可怕的朦朦胧胧的意识 梦里都梦到她好',
      replys:{
        id:2,//评论id
        userId:1002,
        userNickName:'痴心的人',
        parentId:null,
        parentNickName:null,
        comment:'做人要厚道',
      }
    },
    {
      id:13,//当前评论的id
      userId:101,//作者id,娇友id
      userIcon:'e5.jpg',//作者头像，娇友头像
      userNickName:'小萝莉',//作者昵称
      publishTime:'2018-08-20 08:10:00',
      sex:1,//0男1女2不限
      age:23,
      vipType:'SVIP3',
      deposit:1,//保证金
      demand:{
        idcard:1,
        car:1,
        house:0,
        health:0
      },
      reply:'564',//评论的回复数
      praise:'132',//评论的点赞数
      myPraise:0,//当前用户是否点赞0否1是
      replyContent:'有人问我思念到极致是什么感觉。 我曾经发了句晚安给她 一晚上醒来七次看手机信息。 就是那种可怕的朦朦胧胧的意识 梦里都梦到她好',
      replys:{
        id:3,//评论id
        userId:1001,
        userNickName:'痴心的人',
        parentId:null,
        parentNickName:null,
        comment:'做人要厚道',
      }
    },
    {
      id:14,//当前评论的id
      userId:101,//作者id,娇友id
      userIcon:'e5.jpg',//作者头像，娇友头像
      userNickName:'小萝莉',//作者昵称
      publishTime:'2018-08-20 08:10:00',
      sex:1,//0男1女2不限
      age:23,
      vipType:'SVIP3',
      deposit:1,//保证金
      demand:{
        idcard:1,
        car:1,
        house:0,
        health:0
      },
      reply:'564',//评论的回复数
      praise:'132',//评论的点赞数
      myPraise:0,//当前用户是否点赞0否1是
      replyContent:'有人问我思念到极致是什么感觉。 我曾经发了句晚安给她 一晚上醒来七次看手机信息。 就是那种可怕的朦朦胧胧的意识 梦里都梦到她好',
      replys:{
        id:4,//评论id
        userId:1001,
        userNickName:'痴心的人',
        parentId:null,
        parentNickName:null,
        comment:'做人要厚道',
      }
    },
    {
      id:15,//当前评论的id
      userId:101,//作者id,娇友id
      userIcon:'e5.jpg',//作者头像，娇友头像
      userNickName:'小萝莉',//作者昵称
      publishTime:'2018-08-20 08:10:00',
      sex:1,//0男1女2不限
      age:23,
      vipType:'SVIP3',
      deposit:1,//保证金
      demand:{
        idcard:1,
        car:1,
        house:0,
        health:0
      },
      reply:'564',//评论的回复数
      praise:'132',//评论的点赞数
      myPraise:0,//当前用户是否点赞0否1是
      replyContent:'有人问我思念到极致是什么感觉。 我曾经发了句晚安给她 一晚上醒来七次看手机信息。 就是那种可怕的朦朦胧胧的意识 梦里都梦到她好',
      replys:{
        id:5,//评论id
        userId:1001,
        userNickName:'痴心的人',
        parentId:null,
        parentNickName:null,
        comment:'做人要厚道',
      }
    },
    {
      id:16,//当前评论的id
      userId:101,//作者id,娇友id
      userIcon:'e5.jpg',//作者头像，娇友头像
      userNickName:'小萝莉',//作者昵称
      publishTime:'2018-08-20 08:10:00',
      sex:1,//0男1女2不限
      age:23,
      vipType:'SVIP3',
      deposit:1,//保证金
      demand:{
        idcard:1,
        car:1,
        house:0,
        health:0
      },
      reply:'564',//评论的回复数
      praise:'132',//评论的点赞数
      myPraise:0,//当前用户是否点赞0否1是
      replyContent:'有人问我思念到极致是什么感觉。 我曾经发了句晚安给她 一晚上醒来七次看手机信息。 就是那种可怕的朦朦胧胧的意识 梦里都梦到她好',
      replys:{
        id:6,//评论id
        userId:1001,
        userNickName:'痴心的人',
        parentId:null,
        parentNickName:null,
        comment:'做人要厚道',
      }
    },
    {
      id:17,//当前评论的id
      userId:101,//作者id,娇友id
      userIcon:'e5.jpg',//作者头像，娇友头像
      userNickName:'小萝莉',//作者昵称
      publishTime:'2018-08-20 08:10:00',
      sex:1,//0男1女2不限
      age:23,
      vipType:'SVIP3',
      deposit:1,//保证金
      demand:{
        idcard:1,
        car:1,
        house:0,
        health:0
      },
      reply:'564',//评论的回复数
      praise:'132',//评论的点赞数
      myPraise:0,//当前用户是否点赞0否1是
      replyContent:'有人问我思念到极致是什么感觉。 我曾经发了句晚安给她 一晚上醒来七次看手机信息。 就是那种可怕的朦朦胧胧的意识 梦里都梦到她好',
      replys:{
        id:7,//评论id
        userId:1001,
        userNickName:'痴心的人',
        parentId:null,
        parentNickName:null,
        comment:'做人要厚道',
      }
    },
    {
      id:18,//当前评论的id
      userId:101,//作者id,娇友id
      userIcon:'e5.jpg',//作者头像，娇友头像
      userNickName:'小萝莉',//作者昵称
      publishTime:'2018-08-20 08:10:00',
      sex:1,//0男1女2不限
      age:23,
      vipType:'SVIP3',
      deposit:1,//保证金
      demand:{
        idcard:1,
        car:1,
        house:0,
        health:0
      },
      reply:'564',//评论的回复数
      praise:'132',//评论的点赞数
      myPraise:0,//当前用户是否点赞0否1是
      replyContent:'有人问我思念到极致是什么感觉。 我曾经发了句晚安给她 一晚上醒来七次看手机信息。 就是那种可怕的朦朦胧胧的意识 梦里都梦到她好',
      replys:{
        id:8,//评论id
        userId:1001,
        userNickName:'痴心的人',
        parentId:null,
        parentNickName:null,
        comment:'做人要厚道',
      }
    },
    {
      id:19,//当前评论的id
      userId:101,//作者id,娇友id
      userIcon:'e5.jpg',//作者头像，娇友头像
      userNickName:'小萝莉',//作者昵称
      publishTime:'2018-08-20 08:10:00',
      sex:1,//0男1女2不限
      age:23,
      vipType:'SVIP3',
      deposit:1,//保证金
      demand:{
        idcard:1,
        car:1,
        house:0,
        health:0
      },
      reply:'564',//评论的回复数
      praise:'132',//评论的点赞数
      myPraise:0,//当前用户是否点赞0否1是
      replyContent:'有人问我思念到极致是什么感觉。 我曾经发了句晚安给她 一晚上醒来七次看手机信息。 就是那种可怕的朦朦胧胧的意识 梦里都梦到她好',
      replys:{
        id:9,//评论id
        userId:1001,
        userNickName:'痴心的人',
        parentId:null,
        parentNickName:null,
        comment:'做人要厚道',
      }
    },
  ]
}
