//let actId=['44a8772d3a33475dbf0f9cc67447cde9','333a3f3f6b944b5ca271e72ebd7efdf5','0fe7d9dbc1414c58850e97ccd9d806db','604a7e0fbc12413faf5e98633df0c1a5','15f5b21d72a0476cbae97cdd71273ccd','b00420d0ed98404994dcd3a94e20299a','67cc0fbc61064013a05159a7a13cc5e3','7dcf7c14ec24431298a3d92b266b5f9f','0900644ac0c14f68b436be3a893ecd58','f91e448d364811e9a06f00163e046f71','17ebf78b33f04b9aa9a7252c78e9c640','6fe90619b51541aa8f0c39f853c470df','cfed937dc2cb4ca6aae39fe5680f25cc','c5c380ea93cb4d4b88409fb84b80cc52','562ad9a99da94d3387a24b5d5ecd0331'];

let actContent={//弃用
	'44a8772d3a33475dbf0f9cc67447cde9':{
		name:"“乾坤有爱-玫瑰相约”广州单身职工新年相亲会",
		shareTitle:"“乾坤有爱-玫瑰相约”广州单身职工新年相亲会",
		shareDesc:"2019年1月5日“乾坤有爱-玫瑰相约”广州单身职工新年相亲会",
		taskId:"",
		followCount:"188",
		styles:"margin-bottom: 0;",//ul的样式
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/static_02.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/static_03.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/static_04.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/static_05_2.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/static_06_2.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/static_07.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/static_08_2.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/static_09_2.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/static_10_2.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/static_11_2.jpg",styles:""},
			],
			gifs:{//图片组里包含的gif动画图片
				"p3":[{
					src:"static/activityDetailStatic/gif1.gif",
					styles:"width: 8.48rem;margin-top: 1.95rem",
				}],
				"p4":[{
					src:"static/activityDetailStatic/gif2.gif",
					styles:"width: 6.74rem;margin-top: 2.05rem",
				}]
			},
			routerLink:{//图片组里包含的routerLink跳转
				"p9":[
					{name:"activityDetailStatic",
						query:{id:'0fe7d9dbc1414c58850e97ccd9d806db'},
						styles:"width:50%;height:5rem;margin-top:1.2rem;"
					},{name:"activityDetailStatic",
						query:{id:'333a3f3f6b944b5ca271e72ebd7efdf5'},
						styles:"width:50%;height:5rem;margin-top:1.2rem;"
					}
				]
			}
		}
	},
	'333a3f3f6b944b5ca271e72ebd7efdf5':{
		name:"“乾坤有爱-旅行有情”两天一夜单身旅行",
		shareTitle:"“乾坤有爱-旅行有情”两天一夜单身旅行",
		shareDesc:"2019年2月16日“乾坤有爱-旅行有情”两天一夜单身旅行",
		taskId:"37",
		followCount:"188",
		styles:"margin-bottom: 0.8rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/s2_1.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/s2_2.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/s2_3.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/s2_4_2.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/s2_5.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/s2_6_2.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/s2_7.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/s2_8.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/s2_9.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/s2_10.jpg",styles:""},
				{id:"p11",src:"static/activityDetailStatic/s2_11.jpg",styles:""},
				{id:"p12",src:"static/activityDetailStatic/s2_12.jpg",styles:""},
				{id:"p13",src:"static/activityDetailStatic/s2_13.jpg",styles:""},
				{id:"p14",src:"static/activityDetailStatic/s2_14.jpg",styles:""},
				{id:"p15",src:"static/activityDetailStatic/s_b.jpg",styles:""},
			],
			gifs:{//图片组里包含的gif动画图片
				"p13":[{
					src:"static/activityDetailStatic/s2_gif_1.gif",
					styles:"width: 5rem;margin-top: 0.65rem;",
				}],
			},
			routerLink:{//图片组里包含的routerLink跳转
				"p14":[
					{name:"activityDetailStatic",
						query:{id:'44a8772d3a33475dbf0f9cc67447cde9'},
						styles:"width:50%;height:5rem;margin-top:1.5rem;"
					},{name:"activityDetailStatic",
						query:{id:'0fe7d9dbc1414c58850e97ccd9d806db'},
						styles:"width:50%;height:5rem;margin-top:1.5rem;"
					}
				]
			}
		}
	},
	'0fe7d9dbc1414c58850e97ccd9d806db':{
		name:"“乾坤有爱-玲珑相约”周末24小时高质量单身聚会",
		shareTitle:"“乾坤有爱-玲珑相约”周末24小时高质量单身聚会",
		shareDesc:"2019年1月12日“乾坤有爱-玲珑相约”周末24小时高质量单身聚会",
		taskId:"36",
		followCount:"188",
		styles:"margin-bottom: 0.8rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/s1_1.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/s1_2.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/s1_3.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/s1_4.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/s1_5.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/s1_6.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/s1_7.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/s1_8.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/s_b.jpg",styles:""},
			],
			gifs:{//图片组里包含的gif动画图片
				"p3":[{
					src:"static/activityDetailStatic/s1_gif_1.gif",
					styles:"width: 2.7rem;margin-top: 8.33rem;",
				}],
				"p4":[{
					src:"static/activityDetailStatic/s1_gif_2.gif",
					styles:"width: 7.16rem;margin-top: 1.92rem;",
				}],
			},
			routerLink:{//图片组里包含的routerLink跳转
				"p8":[
					{name:"activityDetailStatic",
						query:{id:'44a8772d3a33475dbf0f9cc67447cde9'},
						styles:"width:50%;height:5rem;margin-top:8rem;"
					},{name:"activityDetailStatic",
						query:{id:'333a3f3f6b944b5ca271e72ebd7efdf5'},
						styles:"width:50%;height:5rem;margin-top:8rem;"
					}
				]
			}
		}
	},
	'604a7e0fbc12413faf5e98633df0c1a5':{
		name:"“乾坤有爱•月老在线”系列-线上相亲活动（青年专场）",
		shareTitle:"“乾坤有爱•月老在线”系列-线上相亲活动（青年专场）",
		shareDesc:"青年专场：年龄在22-35岁单身，报名人数：500人",
		taskId:"41",
		followCount:"188",
		styles:"margin-bottom: 0;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/qn_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/qn_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/ylzx_01.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/ylzx_02.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/ylzx_03.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/qn_04.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/qn_05.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/ylzx_06.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/ylzx_07.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/ylzx_08.jpg",styles:""},
				{id:"p11",src:"",styles:""},
				{id:"p12",src:"static/activityDetailStatic/ylzx_10.jpg",styles:""},
			],
			imgs:{//图片组里包含的多张图片
				"p11":[{
						src:"static/activityDetailStatic/onb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/onb2.jpg",
						styles:"width:3.47rem;float:left;display:block;",
					},{
						src:"static/activityDetailStatic/onb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
		}
	},
	'15f5b21d72a0476cbae97cdd71273ccd':{
		name:"“乾坤有爱--月老在线”系列-线上相亲活动（二度缘专场）",
		shareTitle:"“乾坤有爱--月老在线”系列-线上相亲活动（二度缘专场）",
		shareDesc:"二度缘：有过婚史和大龄青年",
		taskId:"43",
		followCount:"188",
		styles:"margin-bottom: 0;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/edy_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/edy_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/ylzx_01.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/ylzx_02.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/ylzx_03.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/edy_04.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/edy_05.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/ylzx_06.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/ylzx_07.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/ylzx_08.jpg",styles:""},
				{id:"p11",src:"",styles:""},
				{id:"p12",src:"static/activityDetailStatic/ylzx_10.jpg",styles:""},
			],
			imgs:{//图片组里包含的多张图片
				"p11":[{
						src:"static/activityDetailStatic/onb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/onb2.jpg",
						styles:"width:3.47rem;float:left;display:block;",
					},{
						src:"static/activityDetailStatic/onb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
		}
	},
	'b00420d0ed98404994dcd3a94e20299a':{
		name:"“乾坤有爱--月老在线”系列-线上相亲活动（大龄专场）",
		shareTitle:"“乾坤有爱--月老在线”系列-线上相亲活动（大龄专场）",
		shareDesc:"大龄专场：年龄大于30岁单身",
		taskId:"42",
		followCount:"188",
		styles:"margin-bottom: 0;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/dl_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/dl_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/ylzx_01.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/ylzx_02.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/ylzx_03.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/dl_04.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/dl_05.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/ylzx_06.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/ylzx_07.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/ylzx_08.jpg",styles:""},
				{id:"p11",src:"",styles:""},
				{id:"p12",src:"static/activityDetailStatic/ylzx_10.jpg",styles:""},
			],
			imgs:{//图片组里包含的多张图片
				"p11":[{
						src:"static/activityDetailStatic/onb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/onb2.jpg",
						styles:"width:3.47rem;float:left;display:block;",
					},{
						src:"static/activityDetailStatic/onb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
		}
	},
	'67cc0fbc61064013a05159a7a13cc5e3':{
		name:"“乾坤有爱•情牵常春藤”大型红酒相亲舞会",
		shareTitle:"“乾坤有爱•情牵常春藤”大型红酒相亲舞会",
		shareDesc:"“乾坤有爱•情牵常春藤”大型红酒相亲舞会",
		taskId:"44",
		followCount:"188",
		styles:"margin-bottom: 0;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/xxcc_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/xxcc_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/xxcc_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/xxcc_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/xxcc_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/xxcc_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/xxcc_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/xxcc_08_2.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/xxcc_09.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/xxcc_10.jpg",styles:""},
				{id:"p11",src:"static/activityDetailStatic/xxcc_11.jpg",styles:""},
				{id:"p12",src:"static/activityDetailStatic/xxcc_12.jpg",styles:""},
				{id:"p13",src:"static/activityDetailStatic/xxcc_13.jpg",styles:""},
				{id:"p14",src:"static/activityDetailStatic/xxcc_14.jpg",styles:""},
				{id:"p15",src:"static/activityDetailStatic/xxcc_15.jpg",styles:""},
				{id:"p16",src:"",styles:""},
			],
			gifs:{//图片组里包含的gif动画图片
				"p14":[{
					src:"static/activityDetailStatic/jh_1.gif",
					styles:"width: 6rem;margin-top: 2.8rem;",
				}],
				"p15":[{
					src:"static/activityDetailStatic/jh_2.gif",
					styles:"width: 4.19rem;margin-top: 1.16rem;",
				}],
			},
			imgs:{//图片组里包含的多张图片
				"p16":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
		}
	},
	'7dcf7c14ec24431298a3d92b266b5f9f':{
		name:"“乾坤有爱•眉目传情”系列现场相亲活动（二度缘专场）",
		shareTitle:"“乾坤有爱•眉目传情”系列现场相亲活动（二度缘专场）",
		shareDesc:"“乾坤有爱•眉目传情”系列现场相亲活动（二度缘专场）",
		taskId:"46",
		followCount:"188",
		styles:"margin-bottom: 0;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/xxed_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/xxed_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/xxed_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/xxed_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/xxed_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/xxed_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/xxed_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/xxed_08.jpg",styles:""},
				{id:"p9",src:"",styles:""},
			],
			gifs:{//图片组里包含的gif动画图片
				"p3":[{
					src:"static/activityDetailStatic/xxed.gif",
					styles:"width: 5rem;margin-top: 5.2rem;",
				}],
			},
			imgs:{//图片组里包含的多张图片
				"p9":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
		}
	},
	'0900644ac0c14f68b436be3a893ecd58':{
		name:"“乾坤有爱•眉目传情”系列现场相亲活动（三高专场）",
		shareTitle:"“乾坤有爱•眉目传情”系列现场相亲活动（三高专场）",
		shareDesc:"“乾坤有爱•眉目传情”系列现场相亲活动（三高专场）",
		taskId:"45",
		followCount:"188",
		styles:"margin-bottom: 1rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/xxsg_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/xxsg_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/xxsg_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/xxsg_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/xxsg_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/xxsg_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/xxsg_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/xxsg_08.jpg",styles:""},
				{id:"p9",src:"",styles:""},
			],
			gifs:{//图片组里包含的gif动画图片
				"p2":[{
					src:"static/activityDetailStatic/xxsg.gif",
					styles:"width: 3.2rem;margin-top: 3.3rem;",
				}],
			},
			imgs:{//图片组里包含的多张图片
				"p9":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
		}
	},
	'f91e448d364811e9a06f00163e046f71':{
		name:"“乾坤有爱•眉目传情”系列现场相亲活动（红酒民谣单身派对）",
		shareTitle:"“乾坤有爱•眉目传情”系列现场相亲活动（红酒民谣单身派对）",
		shareDesc:"“乾坤有爱•眉目传情”系列现场相亲活动（红酒民谣单身派对）",
		taskId:"",
		followCount:"188",
		styles:"margin-bottom: 1rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/sged/sged_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/sged/sged_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/sged/sged_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/sged/sged_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/sged/sged_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/sged/sged_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/sged/sged_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/sged/sged_08.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/sged/sged_09.jpg",styles:""},
				{id:"p10",src:"",styles:""},
			],
			gifs:{//图片组里包含的gif动画图片
				"p2":[{
					src:"static/activityDetailStatic/xxsg.gif",
					styles:"width: 3.2rem;margin-top: 2.88rem;",
				}],
			},
			imgs:{//图片组里包含的多张图片
				"p10":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
		}
	},
	'17ebf78b33f04b9aa9a7252c78e9c640':{
		name:"“乾坤有爱-月老在线”女神驾到线上相亲活动（二)",
		shareTitle:"“乾坤有爱-月老在线”女神驾到线上相亲活动（二)",
		shareDesc:"“乾坤有爱-月老在线”女神驾到线上相亲活动（二)",
		taskId:"",
		followCount:"188",
		styles:"margin-bottom: 1rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/nsjd2/nsjd2_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/nsjd2/nsjd2_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/nsjd2/nsjd2_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/nsjd2/nsjd2_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/nsjd2/nsjd2_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/nsjd2/nsjd2_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/nsjd2/nsjd2_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/nsjd2/nsjd2_08.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/nsjd2/nsjd2_09.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/nsjd2/nsjd2_10.jpg",styles:""},
				{id:"p11",src:"static/activityDetailStatic/nsjd2/nsjd2_11.jpg",styles:""},
				{id:"p12",src:"static/activityDetailStatic/nsjd2/nsjd2_12.jpg",styles:""},
				{id:"p13",src:"static/activityDetailStatic/nsjd2/nsjd2_13.jpg",styles:""},
				{id:"p14",src:"static/activityDetailStatic/nsjd2/nsjd2_14.jpg",styles:""},
				{id:"p15",src:"static/activityDetailStatic/nsjd2/nsjd2_15.jpg",styles:""},
				{id:"p16",src:"static/activityDetailStatic/nsjd2/nsjd2_16.jpg",styles:""},
				{id:"p17",src:"static/activityDetailStatic/nsjd2/nsjd2_17.jpg",styles:""},
				{id:"p18",src:"static/activityDetailStatic/nsjd2/nsjd2_18.jpg",styles:""},
				{id:"p19",src:"static/activityDetailStatic/nsjd2/nsjd2_19.jpg",styles:""},
				{id:"p20",src:"static/activityDetailStatic/nsjd2/nsjd2_20.jpg",styles:""},
				{id:"p21",src:"static/activityDetailStatic/nsjd2/nsjd2_21.jpg",styles:""},
				{id:"p22",src:"static/activityDetailStatic/nsjd2/nsjd2_22.jpg",styles:""},
				{id:"p23",src:"static/activityDetailStatic/nsjd2/nsjd2_23.jpg",styles:""},
				{id:"p24",src:"static/activityDetailStatic/hg.jpg",styles:"padding-top:1rem;"},
				{id:"p25",src:"",styles:""},
			],
			imgs:{//图片组里包含的多张图片
				"p25":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
			aLink:{//外链
				"p24":[
					{href:"https://mp.weixin.qq.com/s/sYXgy-qTPQgNvuJgjLcWgw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/IZbQJ1_ysAuCcky3XRKCCw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/GbQ9uySVYxHsS6N1p5467Q",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/jYZppwZul-YqVMO_Z-Q8Fw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					}
				]
			},
			routerLink:{//图片组里包含的routerLink跳转
				"p23":[
					{name:"activityDetailStatic",
						query:{id:'cfed937dc2cb4ca6aae39fe5680f25cc'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'c5c380ea93cb4d4b88409fb84b80cc52'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'6fe90619b51541aa8f0c39f853c470df'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					}
				]
			}
		}
	},
	'6fe90619b51541aa8f0c39f853c470df':{
		name:"“乾坤有爱-旅途有情”花果山单身旅行一日游",
		shareTitle:"“乾坤有爱-旅途有情”花果山单身旅行一日游",
		shareDesc:"“乾坤有爱-旅途有情”花果山单身旅行一日游",
		taskId:"",
		followCount:"188",
		styles:"margin-bottom: 1rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/hgs/hgs_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/hgs/hgs_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/hgs/hgs_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/hgs/hgs_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/hgs/hgs_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/hgs/hgs_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/hgs/hgs_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/hgs/hgs_08.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/hgs/hgs_09.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/hgs/hgs_10.jpg",styles:""},
				{id:"p11",src:"static/activityDetailStatic/hgs/hgs_11.jpg",styles:""},
				{id:"p12",src:"static/activityDetailStatic/hgs/hgs_12.jpg",styles:""},
				{id:"p13",src:"static/activityDetailStatic/hgs/hgs_13.jpg",styles:""},
				{id:"p14",src:"static/activityDetailStatic/hgs/hgs_14.jpg",styles:""},
				{id:"p15",src:"static/activityDetailStatic/hgs/hgs_15.jpg",styles:""},
				{id:"p16",src:"static/activityDetailStatic/hgs/hgs_16.jpg",styles:""},
				{id:"p17",src:"static/activityDetailStatic/hgs/hgs_17.jpg",styles:""},
				{id:"p18",src:"static/activityDetailStatic/hgs/hgs_18.jpg",styles:""},
				{id:"p19",src:"static/activityDetailStatic/hgs/hgs_19.jpg",styles:""},
				{id:"p20",src:"static/activityDetailStatic/hgs/hgs_20.jpg",styles:""},
				{id:"p21",src:"static/activityDetailStatic/hgs/hgs_21.jpg",styles:""},
				{id:"p22",src:"static/activityDetailStatic/hgs/hgs_22.jpg",styles:""},
				{id:"p23",src:"static/activityDetailStatic/hgs/hgs_23.jpg",styles:""},
				{id:"p24",src:"static/activityDetailStatic/hgs/hgs_24.jpg",styles:""},
				{id:"p25",src:"static/activityDetailStatic/hgs/hgs_25.jpg",styles:""},
				{id:"p26",src:"static/activityDetailStatic/hg.jpg",styles:"padding-top:1rem;"},
				{id:"p27",src:"",styles:""},
			],
			imgs:{//图片组里包含的多张图片
				"p27":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
			aLink:{//外链
				"p26":[
					{href:"https://mp.weixin.qq.com/s/sYXgy-qTPQgNvuJgjLcWgw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/IZbQJ1_ysAuCcky3XRKCCw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/GbQ9uySVYxHsS6N1p5467Q",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/jYZppwZul-YqVMO_Z-Q8Fw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					}
				]
			},
			routerLink:{//图片组里包含的routerLink跳转
				"p25":[
					{name:"activityDetailStatic",
						query:{id:'cfed937dc2cb4ca6aae39fe5680f25cc'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'c5c380ea93cb4d4b88409fb84b80cc52'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'17ebf78b33f04b9aa9a7252c78e9c640'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					}
				]
			}
		}
	},
	'cfed937dc2cb4ca6aae39fe5680f25cc':{
		name:"“乾坤有爱-月老在线”女神驾到线上相亲活动（一)",
		shareTitle:"“乾坤有爱-月老在线”女神驾到线上相亲活动（一)",
		shareDesc:"“乾坤有爱-月老在线”女神驾到线上相亲活动（一)",
		taskId:"",
		followCount:"188",
		styles:"margin-bottom: 1rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/nsjd1/nsjd1_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/nsjd1/nsjd1_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/nsjd1/nsjd1_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/nsjd1/nsjd1_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/nsjd1/nsjd1_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/nsjd1/nsjd1_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/nsjd1/nsjd1_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/nsjd1/nsjd1_08.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/nsjd1/nsjd1_09.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/nsjd1/nsjd1_10.jpg",styles:""},
				{id:"p11",src:"static/activityDetailStatic/nsjd1/nsjd1_11.jpg",styles:""},
				{id:"p12",src:"static/activityDetailStatic/nsjd1/nsjd1_12.jpg",styles:""},
				{id:"p13",src:"static/activityDetailStatic/nsjd1/nsjd1_13.jpg",styles:""},
				{id:"p14",src:"static/activityDetailStatic/nsjd1/nsjd1_14.jpg",styles:""},
				{id:"p15",src:"static/activityDetailStatic/nsjd1/nsjd1_15.jpg",styles:""},
				{id:"p16",src:"static/activityDetailStatic/nsjd1/nsjd1_16.jpg",styles:""},
				{id:"p17",src:"static/activityDetailStatic/nsjd1/nsjd1_17.jpg",styles:""},
				{id:"p18",src:"static/activityDetailStatic/nsjd1/nsjd1_18.jpg",styles:""},
				{id:"p19",src:"static/activityDetailStatic/nsjd1/nsjd1_19.jpg",styles:""},
				{id:"p20",src:"static/activityDetailStatic/nsjd1/nsjd1_20.jpg",styles:""},
				{id:"p21",src:"static/activityDetailStatic/nsjd1/nsjd1_21.jpg",styles:""},
				{id:"p22",src:"static/activityDetailStatic/nsjd1/nsjd1_22.jpg",styles:""},
				{id:"p23",src:"static/activityDetailStatic/nsjd1/nsjd1_23.jpg",styles:""},
				{id:"p24",src:"static/activityDetailStatic/hg.jpg",styles:"padding-top:1rem;"},
				{id:"p25",src:"",styles:""},
			],
			imgs:{//图片组里包含的多张图片
				"p25":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
			aLink:{//外链
				"p24":[
					{href:"https://mp.weixin.qq.com/s/sYXgy-qTPQgNvuJgjLcWgw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/IZbQJ1_ysAuCcky3XRKCCw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/GbQ9uySVYxHsS6N1p5467Q",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/jYZppwZul-YqVMO_Z-Q8Fw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					}
				]
			},
			routerLink:{//图片组里包含的routerLink跳转
				"p23":[
					{name:"activityDetailStatic",
						query:{id:'c5c380ea93cb4d4b88409fb84b80cc52'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'17ebf78b33f04b9aa9a7252c78e9c640'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'6fe90619b51541aa8f0c39f853c470df'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					}
				]
			}
		}
	},
	'c5c380ea93cb4d4b88409fb84b80cc52':{
		name:"“乾坤有爱-眉目传情”蒙面单身派对",
		shareTitle:"“乾坤有爱-眉目传情”蒙面单身派对",
		shareDesc:"“乾坤有爱-眉目传情”蒙面单身派对",
		taskId:"",
		followCount:"188",
		styles:"margin-bottom: 1rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/mm/mm_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/mm/mm_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/mm/mm_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/mm/mm_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/mm/mm_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/mm/mm_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/mm/mm_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/mm/mm_08.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/mm/mm_09.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/mm/mm_10.jpg",styles:""},
				{id:"p11",src:"static/activityDetailStatic/mm/mm_11.jpg",styles:""},
				{id:"p12",src:"static/activityDetailStatic/mm/mm_12.jpg",styles:""},
				{id:"p13",src:"static/activityDetailStatic/hg.jpg",styles:"padding-top:1rem;"},
				{id:"p14",src:"",styles:""},
			],
			imgs:{//图片组里包含的多张图片
				"p14":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
			aLink:{//外链
				"p13":[
					{href:"https://mp.weixin.qq.com/s/sYXgy-qTPQgNvuJgjLcWgw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/IZbQJ1_ysAuCcky3XRKCCw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/GbQ9uySVYxHsS6N1p5467Q",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/jYZppwZul-YqVMO_Z-Q8Fw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					}
				]
			},
			routerLink:{//图片组里包含的routerLink跳转
				"p12":[
					{name:"activityDetailStatic",
						query:{id:'cfed937dc2cb4ca6aae39fe5680f25cc'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'17ebf78b33f04b9aa9a7252c78e9c640'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'6fe90619b51541aa8f0c39f853c470df'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					}
				]
			}
		}
	},
	'562ad9a99da94d3387a24b5d5ecd0331':{
		name:"“乾坤有爱-眉目传情”单身浪漫派对",
		shareTitle:"“乾坤有爱-眉目传情”单身浪漫派对",
		shareDesc:"“乾坤有爱-眉目传情”单身浪漫派对",
		taskId:"",
		followCount:"188",
		styles:"margin-bottom: 1rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/dg/dg_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/dg/dg_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/dg/dg_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/dg/dg_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/dg/dg_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/dg/dg_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/dg/dg_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/dg/dg_08.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/dg/dg_09_2.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/dg/dg_10.jpg",styles:""},
				{id:"p11",src:"static/activityDetailStatic/dg/dg_11.jpg",styles:""},
				{id:"p12",src:"static/activityDetailStatic/dg/dg_12.jpg",styles:""},
				{id:"p13",src:"static/activityDetailStatic/dg/dg_13.jpg",styles:""},
				{id:"p14",src:"static/activityDetailStatic/dg/dg_14.jpg",styles:""},
				{id:"p15",src:"static/activityDetailStatic/hg.jpg",styles:"padding-top:1rem;"},
				{id:"p16",src:"",styles:""},
			],
			imgs:{//图片组里包含的多张图片
				"p16":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
			aLink:{//外链
				"p15":[
					{href:"https://mp.weixin.qq.com/s/sYXgy-qTPQgNvuJgjLcWgw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/IZbQJ1_ysAuCcky3XRKCCw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/GbQ9uySVYxHsS6N1p5467Q",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/jYZppwZul-YqVMO_Z-Q8Fw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					}
				]
			}
		}
	},
	'da786fb0388c4a58bded2e73aea285c7':{
		name:"“乾坤有爱-月老在线”线上相亲活动（上海专场）",
		shareTitle:"“乾坤有爱-月老在线”线上相亲活动（上海专场）",
		shareDesc:"“乾坤有爱-月老在线”线上相亲活动（上海专场）",
		taskId:"",
		followCount:"188",
		styles:"margin-bottom: 1rem;",
		content:{
			styles:"",//li的样式
			pic:[//内容的图片组
				{id:"p1",src:"static/activityDetailStatic/nsjd1/nsjd1_01.jpg",styles:""},
				{id:"p2",src:"static/activityDetailStatic/nsjd1/nsjd1_02.jpg",styles:""},
				{id:"p3",src:"static/activityDetailStatic/nsjd1/nsjd1_03.jpg",styles:""},
				{id:"p4",src:"static/activityDetailStatic/sh/sh_04.jpg",styles:""},
				{id:"p5",src:"static/activityDetailStatic/sh/sh_05.jpg",styles:""},
				{id:"p6",src:"static/activityDetailStatic/nsjd1/nsjd1_06.jpg",styles:""},
				{id:"p7",src:"static/activityDetailStatic/nsjd1/nsjd1_07.jpg",styles:""},
				{id:"p8",src:"static/activityDetailStatic/nsjd1/nsjd1_08.jpg",styles:""},
				{id:"p9",src:"static/activityDetailStatic/nsjd1/nsjd1_09.jpg",styles:""},
				{id:"p10",src:"static/activityDetailStatic/nsjd1/nsjd1_10.jpg",styles:""},
				{id:"p11",src:"static/activityDetailStatic/nsjd1/nsjd1_11.jpg",styles:""},
				{id:"p12",src:"static/activityDetailStatic/nsjd1/nsjd1_12.jpg",styles:""},
				{id:"p13",src:"static/activityDetailStatic/nsjd1/nsjd1_13.jpg",styles:""},
				{id:"p14",src:"static/activityDetailStatic/nsjd1/nsjd1_14.jpg",styles:""},
				{id:"p15",src:"static/activityDetailStatic/nsjd1/nsjd1_15.jpg",styles:""},
				{id:"p16",src:"static/activityDetailStatic/nsjd1/nsjd1_16.jpg",styles:""},
				{id:"p17",src:"static/activityDetailStatic/nsjd1/nsjd1_17.jpg",styles:""},
				{id:"p18",src:"static/activityDetailStatic/nsjd1/nsjd1_18.jpg",styles:""},
				{id:"p19",src:"static/activityDetailStatic/nsjd1/nsjd1_19.jpg",styles:""},
				{id:"p20",src:"static/activityDetailStatic/sh/sh_20.jpg",styles:""},
				{id:"p21",src:"static/activityDetailStatic/sh/sh_21.jpg",styles:""},
				{id:"p22",src:"static/activityDetailStatic/nsjd1/nsjd1_22.jpg",styles:""},
				{id:"p23",src:"static/activityDetailStatic/nsjd1/nsjd1_23.jpg",styles:""},
				{id:"p24",src:"static/activityDetailStatic/hg.jpg",styles:"padding-top:1rem;"},
				{id:"p25",src:"",styles:""},
			],
			imgs:{//图片组里包含的多张图片
				"p25":[{
						src:"static/activityDetailStatic/outb1.jpg",
						styles:"width:3.67rem;",
					},{
						src:"static/activityDetailStatic/outb2.jpg",
						styles:"width:3.46rem;",
					},{
						src:"static/activityDetailStatic/outb3.jpg",
						styles:"width:3.66rem;",
					},
				],
			},
			aLink:{//外链
				"p24":[
					{href:"https://mp.weixin.qq.com/s/sYXgy-qTPQgNvuJgjLcWgw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/IZbQJ1_ysAuCcky3XRKCCw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/GbQ9uySVYxHsS6N1p5467Q",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					},{href:"https://mp.weixin.qq.com/s/jYZppwZul-YqVMO_Z-Q8Fw",
						target:"_blank",
						styles:"width:50%;margin-top:0.5rem;height:4rem;"
					}
				]
			},
			routerLink:{//图片组里包含的routerLink跳转
				"p23":[
					{name:"activityDetailStatic",
						query:{id:'c5c380ea93cb4d4b88409fb84b80cc52'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'17ebf78b33f04b9aa9a7252c78e9c640'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					},{name:"activityDetailStatic",
						query:{id:'6fe90619b51541aa8f0c39f853c470df'},
						styles:"width:33.3333%;margin-top:1.5rem;height:4rem;"
					}
				]
			}
		}
	},
}
export  {
	//actId,
	actContent
}
