export default {
  recentVisit:[{
      id:3,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:3,
      attentioned:1,//未关注，1已关注
    },
    {
      id:4,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好我只是比别人摔得更多,才能比别人更好',
      level:3,
      attentioned:0,//未关注，1已关注
    },
    {
      id:5,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
    {
      id:6,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
    {
      id:7,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
    {
      id:8,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
    {
      id:9,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
    {
      id:10,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
    {
      id:11,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
    {
      id:12,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
    {
      id:13,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
    {
      id:14,
      icon:'http://mis.iceinfo.net:8080/jiaoyou/static/zipai.png',
      name:'小萝莉',
      signs:'我只是比别人摔得更多,才能比别人更好',
      level:null,
      attentioned:0,//未关注，1已关注
    },
  ]
}
